<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fee Receipt - {{ $fee->student->name }}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @media print {
            .no-print { display: none; }
            body { background: white; padding: 0; }
        }
        /* Initial letter avatar ke liye style */
        .avatar-circle {
            width: 50px;
            height: 50px;
            background-color: #10b981; /* Tailwind green-500 */
            color: white;
            border-radius: 9999px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
            font-size: 1.25rem;
        }
    </style>
</head>
<body class="bg-gray-100 p-5 sm:p-10">
    <div class="max-w-xl mx-auto bg-white p-8 rounded-[2.5rem] shadow-sm border border-gray-100 relative overflow-hidden">
        
        <div class="absolute top-0 right-0 w-32 h-32 bg-green-50 rounded-full -mr-16 -mt-16"></div>

        <div class="flex justify-between items-start mb-10 relative z-10">
            <div>
                <h1 class="text-2xl font-black text-gray-800 uppercase tracking-tighter">My<span class="text-green-600">School</span></h1>
                <p class="text-[9px] font-bold text-gray-400 uppercase tracking-widest">Official Fee Receipt</p>
            </div>
            <div class="text-right">
                <p class="text-[10px] font-black text-gray-800 uppercase">Receipt #{{ str_pad($fee->id, 5, '0', STR_PAD_LEFT) }}</p>
                <p class="text-[9px] font-bold text-gray-400 uppercase">
                    {{ \Carbon\Carbon::parse($fee->payment_date)->format('d M, Y') }}
                </p>
            </div>
        </div>

        <!-- Student Info Section with Image/Initial Logic -->
        <div class="mb-8 p-5 bg-gray-50 rounded-3xl border border-gray-100 flex items-center gap-4">
            <!-- Image ya Initial ka Logic -->
            <div class="flex-shrink-0">
                @if($fee->student->image)
                    <img src="{{ asset('storage/' . $fee->student->image) }}" class="w-[50px] h-[50px] rounded-full object-cover border-2 border-white shadow-sm">
                @else
                    <div class="avatar-circle">
                        {{ strtoupper(substr($fee->student->name, 0, 1)) }}
                    </div>
                @endif
            </div>

            <div>
                <p class="text-[8px] font-black text-gray-400 uppercase tracking-widest mb-0.5">Received From</p>
                <h2 class="text-lg font-bold text-gray-800 leading-tight">{{ $fee->student->name }}</h2>
                <!-- Course JSON fix: Ab sirf name ayega -->
                <p class="text-[10px] text-gray-500 font-bold uppercase tracking-tight">
                    Course: {{ $fee->student->course->name ?? 'N/A' }}
                </p>
            </div>
        </div>

        <table class="w-full mb-10">
            <thead>
                <tr class="border-b border-gray-100">
                    <th class="text-left py-3 text-[9px] font-black uppercase text-gray-400 tracking-widest">Description</th>
                    <th class="text-right py-3 text-[9px] font-black uppercase text-gray-400 tracking-widest">Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="py-5 text-sm font-bold text-gray-700">Monthly Tuition Fee ({{ $fee->month }})</td>
                    <td class="py-5 text-right text-sm font-black text-gray-800">Rs. {{ number_format($fee->amount) }}</td>
                </tr>
                <tr class="border-t-2 border-gray-900">
                    <td class="py-4 text-[10px] font-black uppercase text-gray-900 tracking-widest">Total Paid</td>
                    <td class="py-4 text-right text-xl font-black text-green-600">Rs. {{ number_format($fee->amount) }}</td>
                </tr>
            </tbody>
        </table>

        <div class="flex justify-between items-end pt-12 mt-10 border-t border-gray-50">
            <div class="flex flex-col">
                <p class="text-[8px] font-black text-gray-400 uppercase tracking-widest mb-4">
                    System Generated By: <br>
                    <span class="text-gray-800 text-[10px]">Ujala Liaquat Ali (Owner)</span>
                </p>
                <div class="text-[7px] text-gray-400 font-bold uppercase tracking-widest leading-tight max-w-[180px]">
                    This is a computer generated receipt and does not require a physical signature. Verified by MySchool System.
                </div>
            </div>

            <div class="text-center w-40">
                <div class="mb-1">
                    <p class="italic text-xl text-indigo-900 opacity-80" style="font-family: 'Brush Script MT', cursive;">
                        Ujala Liaquat Ali
                    </p>
                </div>
                <div class="border-t border-gray-300 pt-1">
                    <p class="text-[9px] font-black text-gray-800 uppercase tracking-widest leading-none">Authorized Signature</p>
                    <p class="text-[8px] font-bold text-teal-600 uppercase mt-1 tracking-tighter">Ujala Liaquat Ali</p>
                </div>
            </div>
        </div>

        <div class="mt-12 flex justify-center no-print">
            <button onclick="window.print()" class="bg-gray-900 text-white px-10 py-3.5 rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-green-600 transition-all shadow-xl shadow-gray-200 active:scale-95">
                Print Official Receipt
            </button>
        </div>
    </div>
</body>
</html>